name: create-release
run-name: Create a new release
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version"
        required: true
        type: string
permissions:
  contents: write
jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Create release package
        run: .github/scripts/create-release.sh "${{ inputs.version }}"
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ inputs.version }}
          name: Release v${{ inputs.version }}
          files: release/*.zip
